@extends('layouts.app')

@php($editing = $recurrence !== null)
@php($kind = old('movement_kind', $editing ? (in_array($recurrence->type, [\App\Enums\MovementType::Transfer, \App\Enums\MovementType::InvestmentContribution], true) ? 'transfer' : $recurrence->type->value) : 'expense'))
@section('title', ($editing ? 'Editar serie' : 'Nueva serie').' en '.$project->name)

@section('content')
    <header class="page-heading page-heading--compact"><div class="page-heading__copy"><a class="back-link" href="{{ route('recurrences.index', $project) }}">← Movimientos recurrentes</a><p class="eyebrow">{{ $project->name }}</p><h1 class="page-heading__title">{{ $editing ? 'Editar serie futura' : 'Nueva serie recurrente' }}</h1><p class="page-heading__intro">{{ $editing ? 'Las apariciones ya creadas conservarán sus datos actuales.' : 'Si la primera fecha ya ha llegado, su movimiento se creará al guardar.' }}</p></div></header>

    <form class="form movement-form" action="{{ $editing ? route('recurrences.update', [$project, $recurrence]) : route('recurrences.store', $project) }}" method="post" data-recurrence-form>
        @csrf
        @if($editing) @method('put') @endif
        <section class="wizard__section"><span class="wizard__step" aria-hidden="true">1</span><div class="wizard__content"><h2 class="wizard__title">Movimiento habitual</h2><div class="form-grid">
            <div class="field"><label class="field__label" for="recurrence-kind">Tipo</label><select class="field__control" id="recurrence-kind" name="movement_kind" data-recurrence-kind required><option value="expense" @selected($kind === 'expense')>Gasto</option><option value="income" @selected($kind === 'income')>Ingreso</option><option value="transfer" @selected($kind === 'transfer')>Transferencia o inversión</option></select></div>
            <div class="field"><label class="field__label" for="recurrence-amount">Importe habitual</label><div class="money-field"><input class="field__control money-field__control" id="recurrence-amount" name="amount" inputmode="decimal" value="{{ old('amount', $editing ? number_format($recurrence->amount_cents / 100, 2, ',', '.') : '') }}" required><span class="money-field__suffix">€</span></div></div>
            <div class="field field--wide"><label class="field__label" for="recurrence-concept">Concepto</label><input class="field__control" id="recurrence-concept" name="concept" value="{{ old('concept', $recurrence?->concept) }}" maxlength="180" placeholder="Ej. Alquiler" required></div>
            <div class="field" data-recurrence-standard><label class="field__label" for="recurrence-category">Categoría</label><select class="field__control" id="recurrence-category" name="category_id" data-recurrence-category><option value="">Selecciona una categoría</option>@foreach($categories as $category)<option value="{{ $category->id }}" data-category-type="{{ $category->type->value }}" @selected((string) old('category_id', $recurrence?->category_id) === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></div>
            <div class="field" data-recurrence-standard><label class="field__label" for="recurrence-subcategory">Subcategoría <span class="field__optional">opcional</span></label><select class="field__control" id="recurrence-subcategory" name="subcategory_id" data-recurrence-subcategory><option value="">Sin subcategoría</option>@foreach($categories as $category)@foreach($category->children as $child)<option value="{{ $child->id }}" data-parent-id="{{ $category->id }}" data-category-type="{{ $child->type->value }}" @selected((string) old('subcategory_id', $recurrence?->subcategory_id) === (string) $child->id)>{{ $child->name }}</option>@endforeach @endforeach</select></div>
            <div class="field"><label class="field__label" for="recurrence-source" data-recurrence-source-label>Cuenta de {{ $kind === 'transfer' ? 'origen' : 'cargo' }}</label><select class="field__control" id="recurrence-source" name="financial_account_id" data-recurrence-source required><option value="">Selecciona una cuenta</option>@foreach($accounts as $account)<option value="{{ $account->id }}" data-account-type="{{ $account->type->value }}" @selected((string) old('financial_account_id', $recurrence?->financial_account_id) === (string) $account->id)>{{ $account->name }} · {{ $account->type->label() }}</option>@endforeach</select></div>
            <div class="field" data-recurrence-transfer><label class="field__label" for="recurrence-destination">Cuenta de destino</label><select class="field__control" id="recurrence-destination" name="destination_account_id" data-recurrence-destination><option value="">Selecciona una cuenta</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string) old('destination_account_id', $recurrence?->destination_account_id) === (string) $account->id)>{{ $account->name }} · {{ $account->type->label() }}</option>@endforeach</select></div>
            <div class="field" data-recurrence-standard><label class="field__label" for="recurrence-payer">Pagado por</label><select class="field__control" id="recurrence-payer" name="paid_by_user_id">@foreach($members as $member)<option value="{{ $member->id }}" @selected((string) old('paid_by_user_id', $recurrence?->paid_by_user_id ?? auth()->id()) === (string) $member->id)>{{ $member->name }}</option>@endforeach</select></div>
            <div class="field" data-recurrence-transfer><label class="field__label" for="recurrence-goal">Objetivo vinculado <span class="field__optional">opcional</span></label><select class="field__control" id="recurrence-goal" name="savings_goal_id" data-recurrence-goal><option value="">Sin objetivo</option>@foreach($goals as $goal)<option value="{{ $goal->id }}" data-account-id="{{ $goal->financial_account_id }}" @selected((string) old('savings_goal_id', $recurrence?->savings_goal_id) === (string) $goal->id)>{{ $goal->name }} · {{ $goal->account->name }}</option>@endforeach</select><small class="field__hint">Al elegirlo, el destino debe ser su cuenta vinculada.</small></div>
            <div class="field field--wide"><label class="field__label" for="recurrence-notes">Notas <span class="field__optional">opcional</span></label><textarea class="field__control field__control--textarea" id="recurrence-notes" name="notes" maxlength="5000">{{ old('notes', $recurrence?->notes) }}</textarea></div>
            @include('movements._tags', ['selectedTagIds' => $recurrence?->tags?->modelKeys() ?? []])
        </div></div></section>

        <section class="wizard__section"><span class="wizard__step" aria-hidden="true">2</span><div class="wizard__content"><h2 class="wizard__title">Calendario</h2><p class="wizard__intro">No se desplazan fechas por fines de semana ni festivos. Un día 31 se adapta al último día de los meses cortos y vuelve al 31 después.</p><div class="form-grid">
            <div class="field"><label class="field__label" for="recurrence-frequency">Frecuencia</label><select class="field__control" id="recurrence-frequency" name="frequency" required>@foreach($frequencies as $frequency)<option value="{{ $frequency->value }}" @selected(old('frequency', $recurrence?->frequency->value ?? 'monthly') === $frequency->value)>{{ $frequency->label() }}</option>@endforeach</select></div>
            <div class="field"><label class="field__label" for="recurrence-start">Inicio de la serie</label><input class="field__control" id="recurrence-start" name="start_on" type="date" value="{{ old('start_on', $recurrence?->start_on?->toDateString() ?? $today) }}" required></div>
            <div class="field"><label class="field__label" for="recurrence-next">Próxima aparición</label><input class="field__control" id="recurrence-next" name="next_occurrence_on" type="date" value="{{ old('next_occurrence_on', $recurrence?->next_occurrence_on?->toDateString() ?? $today) }}" required><small class="field__hint">Puedes cambiar desde qué fecha continúa el futuro de la serie.</small></div>
            <div class="field"><label class="field__label" for="recurrence-end">Fecha final <span class="field__optional">opcional</span></label><input class="field__control" id="recurrence-end" name="ends_on" type="date" value="{{ old('ends_on', $recurrence?->ends_on?->toDateString()) }}"></div>
        </div></div></section>
        <div class="wizard__actions"><a class="button button--secondary" href="{{ route('recurrences.index', $project) }}">Cancelar</a><button class="button button--primary" type="submit">{{ $editing ? 'Guardar serie futura' : 'Crear serie' }}</button></div>
    </form>
@endsection
